data_fetcher:
    ticker: "AAPL"
    start: "2022-01-01"

param_grid:
  n_estimators: [100, 200]
  learning_rate: [0.01, 0.1]
  max_depth: [3, 5]
  subsample: [0.8]
  colsample_bytree: [0.8]

test_size: 0.2