param_grid_xgboost:
    'n_estimators': [200]             
    'learning_rate': [0.01, 0.05, 0.1]         
    'max_depth': [3, 5]                      
    'subsample': [0.6, 0.8, 1.0]                
    'colsample_bytree': [0.6, 0.8, 1.0]         
    'gamma': [0, 1]                            
    'reg_alpha': [0.1, 0.5]                  
    'reg_lambda': [1, 5]                        

param_grid_lightgbm:
  num_leaves: [31, 50]
  learning_rate: [0.01, 0.05, 0.1]
  n_estimators: [100, 200, 500]
  max_depth: [-1, 5, 10]

param_grid_randomforest:
  n_estimators: [100, 200, 500]
  max_depth: [10, 20, None]
  min_samples_split: [2, 5, 10]
  min_samples_leaf: [1, 2, 4]
  max_features: ['sqrt', 'log2']
