data_fetcher:
    ticker: "AAPL"
    start: "2022-01-01"

param_grid:
    'n_estimators': [200]             # Controls the number of trees
    'learning_rate': [0.01, 0.05, 0.1]          # Smaller = slower learning, often better
    'max_depth': [3, 5]                      # Controls complexity of trees
    'subsample': [0.6, 0.8, 1.0]                # Controls row sampling per tree
    'colsample_bytree': [0.6, 0.8, 1.0]         # Controls feature sampling
    'gamma': [0, 1]                             # Minimum loss reduction to make a split
    'reg_alpha': [0.1, 0.5]                  # L1 regularization
    'reg_lambda': [1, 5]                        # L2 regularization


test_size: 0.2

param_grid_lightgbm:
  num_leaves: [31, 50]
  learning_rate: [0.01, 0.05, 0.1]
  n_estimators: [100, 200, 500]
  max_depth: [-1, 5, 10]

param_grid_randomforest:
  n_estimators: [100, 200, 500]
  max_depth: [10, 20, None]
  min_samples_split: [2, 5, 10]
  min_samples_leaf: [1, 2, 4]
  max_features: ['auto', 'sqrt', 'log2']
